Refactor(products endpoint) to consider user and favorites
HackYourFuture-CPH/fp-class22 pull request #120
Opened 2022-12-27 08:35 UTC by Yuliia-Balandiuk

# Description:

Refactor products endpoint to consider user and favorites

# Jira:
https://hackyourfuture-dk.atlassian.net/browse/CLASS22-141

2023-01-06 19:26 UTC, miltonhultgren requested changes

2023-01-06 19:26 UTC, miltonhultgren commented on packages/client/src/components/ProductList/ProductList.component.js
> +  // toggleFavorite,
Please don't comment out code, delete it if it isn't needed and if you change your mind, Git allows you to revert changes.

2023-01-06 19:26 UTC, miltonhultgren commented on packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
> +  let isFavorite;
This is never assigned any value?

2023-01-06 19:26 UTC, miltonhultgren commented on packages/server/api/controllers/products.controller.js
> +  const user = (await knex('users').where({ uid: userUid }))[0];
If there is no such user found that should probably be an error thrown.

2023-01-06 19:26 UTC, miltonhultgren commented on packages/server/api/controllers/users.controllers.js
> +const getUsers = async () => {
Where is this used?

2023-01-08 13:00 UTC, 27ManishaPatel approved these changes, later dismissed

2023-01-08 13:55 UTC, merged