feature(Order endpoint) create order endpoint
HackYourFuture-CPH/fp-class22 pull request #123
Opened 2023-01-03 08:04 UTC by Yuliia-Balandiuk

# Description:

Create an order endpoint for fetch orders with status created by user id

# Jira:
https://hackyourfuture-dk.atlassian.net/browse/CLASS22-128

2023-01-06 19:29 UTC, miltonhultgren requested changes
Isn't this the same work as https://github.com/HackYourFuture-CPH/fp-class22/pull/118?

2023-01-06 19:29 UTC, miltonhultgren commented on packages/server/api/controllers/orders.controller.js
> +  const user = (await knex('users').where({ uid: userUid }))[0];
What if no such user is found or passed in?

2023-01-06 19:29 UTC, miltonhultgren commented on packages/server/api/controllers/orders.controller.js
> +    const favorites = await knex('orders')
orders?

2023-01-08 12:26 UTC, orhantoy approved these changes

2023-01-08 12:28 UTC, 27ManishaPatel approved these changes

2023-01-08 12:29 UTC, merged