Class22-24-body-component
HackYourFuture-CPH/fp-class22 pull request #18
Opened 2022-11-25 19:50 UTC by Hailegebriel22

# Description

Main body component

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-11-25 20:18 UTC, Hanouj submitted a review, later dismissed
over all good work Haile

2022-11-25 20:18 UTC, Hanouj commented on packages/client/src/components/body/body.component.js
> +import WomenAccessories from '../../assets/women-accessories.png';
Hi Haile I can see that you put the images in client/src/assets and then you import them here. 
an easier way to do it, is to use the public folder in the client and then in assets you'd create a folder for ur images 
then you can access it from any folder you are without importing them like that (src="/public/assets/foldername/glass.png")

2022-11-27 07:48 UTC, shpomp approved these changes
❗ Fix capitalisation:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/64137994/204124691-145026bb-a460-4e43-bd61-e10a4238add4.png">

2022-11-27 08:30 UTC, shpomp commented
> ❗ Fix capitalisation:
> <img width="255" alt="image" src="https://user-images.githubusercontent.com/64137994/204124691-145026bb-a460-4e43-bd61-e10a4238add4.png">
> 

@Hailegebriel22 the folders and files should be edited 🙏

2022-11-27 10:36 UTC, shpomp requested changes
> ❗ Fix capitalisation:
> <img width="255" alt="image" src="https://user-images.githubusercontent.com/64137994/204124691-145026bb-a460-4e43-bd61-e10a4238add4.png">
> 

@Hailegebriel22 the folders and files should be edited 🙏

2022-11-27 11:46 UTC, Hanouj approved these changes

2022-11-27 12:21 UTC, Hanouj approved these changes

2022-11-27 13:00 UTC, shpomp approved these changes

2022-11-27 13:01 UTC, merged